In [4]:
# collection, defaultdict and lambda
import numpy as np
from collections import defaultdict

visited_pairs = defaultdict(lambda: np.ones(2))  # {"key": np.array([0, 0])}
print(visited_pairs[1][1])
visited_pairs[1][1] += 1
print(visited_pairs[1][1])

1.0
2.0


In [5]:
# defaultdict means that if a key is not found in the dictionary ...
#     ... then instead of a KeyError being thrown, a new entry is created
d = defaultdict(int)  # specify the type
for k in "abraccadabra":
    d[k] += 1 # no need to check if key exists
d.items()

dict_items([('a', 5), ('b', 2), ('r', 2), ('c', 2), ('d', 1)])

In [7]:
# replace verbose - debug log
# https://docs.python.org/3/howto/logging.html
import logging
import sys
logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)  # level is specified
# if no destination is set, they will set a destination of the console (sys.stderr)
logger_1 = logging.getLogger(__name__)

logger_1.debug('A debug message!')
logger_1.propagate = False
# Child loggers propagate messages up to the handlers associated with their ancestor loggers.
logger_1.info('1/2 - We processed {} records'.format(len([1, 2])))
logger_1.propagate = True
logger_1.info('2/2 - We processed %d records', len([1, 2]))  # uses the old, %-style of string formatting.

# The INFO message doesn’t appear because the default level is WARNING

DEBUG:__main__:A debug message!
INFO:__main__:2/2 - We processed 2 records


In [8]:
# Advanced logging
import logging
logger_2 = logging.getLogger(__name__)
logger_2.setLevel(logging.INFO)  # lowest-severity log message a logger will handle

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt="%Y-%m-%d %H:%M:%S")  # specify the layout of log records in the final output
file_handler = logging.FileHandler("logfile.log")  # Handlers send the log records 
file_handler.setFormatter(formatter)

logger_2.addHandler(file_handler)
logger_2.info('2 - We processed %d records', len([1, 2]))

INFO:__main__:2 - We processed 2 records


In [9]:
# unpack tuple
sar = ((20, 6, True), 0, 1.0)
(state, done, reward) = sar  # unpack
print(state)
print(reward)
print(*sar)  #  *-operator to unpack the arguments out of a list or tuple
state, done, reward = (*sar,)  # unpack
print(state)
print(reward)

(20, 6, True)
1.0
(20, 6, True) 0 1.0
(20, 6, True)
1.0


In [10]:
# product of elements in a list
import gym
import gym.spaces
env = gym.make('Blackjack-v0')
nb_possible_states = np.prod([elem.n for elem in env.observation_space.spaces])

In [11]:
# If-Else one-line
reward = 0.5 
print('You won :)\n') if reward > 0 else print('You lost :(\n')
state = [20]
probs = [0.8, 0.2] if state[0] > 18 else [0.2, 0.8]
action = np.random.choice(np.arange(2), p=probs)

You won :)



In [ ]:
# zip
episode = [((12, 10, False), 1, 0), ((13, 10, False), 1, 0),
           ((20, 10, False), 0, 1.0)]
states, actions, rewards = zip(*episode)
print(actions)
gamma = 2
discounts = [gamma**i for i in range(len(rewards)+1)]
print(discounts)

In [ ]:
# enumerate
for i, state in enumerate(states):
    print(i)
    print(state)
    print(states[i])  # same as state
    print(actions[i])  # way to access the corresponding action

my_list = ['apple', 'banana', 'grapes', 'pear']
# argument = where to start the counter
counter_list = list(enumerate(my_list, 1))
print(counter_list)
# Output: [(1, 'apple'), (2, 'banana'), (3, 'grapes'), (4, 'pear')]

In [ ]:
# clip of decay
epsilon = 1
eps_decay = 0.999
eps_min = 0.05
for i in range(10):
    epsilon = max(epsilon*eps_decay, eps_min)

In [ ]:
# argmax and dict()
Q = defaultdict(lambda: np.zeros(2))
Q[1][0] = 0
Q[1][1] = 1
Q[2][0] = 2
policy = dict((k,np.argmax(v)) for k, v in Q.items())
print(policy)

In [ ]:
# monitor progress
i_episode = 100
num_episodes = 1000
if i_episode % 10 == 0:
    print("\rEpisode {}/{}.".format(i_episode, num_episodes), end="")
    sys.stdout.flush()

In [ ]:
# multiply lists
rewards = np.array([1, 2, 3, 4])
discounts = np.array([1, 1, 1, 1, 1])
i = 1
print(rewards[i:])
print(discounts[:-(1+i)])
print(sum(rewards[i:]*discounts[:-(1+i)]))

In [15]:
print("simon /r 1".rstrip())
'test string\n'.rstrip()

simon /r 1


'test string'

In [ ]:
# np.zeros requires a tuple
V_opt = np.zeros((4,12))
print(V_opt)

In [ ]:
reshape(4,12)

In [5]:
# linspace()
num_episodes = 100
avg_scores = [1, 2, 3, 4, 5]
print(np.linspace(0,num_episodes,len(avg_scores)))

# arange
print(np.arange(3, 8, 2))

[  0.  25.  50.  75. 100.]
[3 5 7]


In [ ]:
import check_test

In [ ]:
# np.arange()
random.choice(np.arange(env.action_space.n))

In [7]:
# deque
from collections import deque
# idea: `avg_rewards[0]` is the average return collected by the agent over the first 100 episodes.
import numpy as np
num_episodes = 3
avg_scores = deque(maxlen=num_episodes)   # average scores over every plot_every episodes
tmp_scores = [10, 12]
avg_scores.append(np.mean(tmp_scores))
tmp_scores = [8, 10]
avg_scores.append(np.mean(tmp_scores))
tmp_scores = [6, 8]
avg_scores.append(np.mean(tmp_scores))
tmp_scores = [4, 6]
avg_scores.append(np.mean(tmp_scores))
print(avg_scores)
print(np.asarray(avg_scores))  # note asarray (not array)

deque([9.0, 7.0, 5.0], maxlen=3)
[9. 7. 5.]


In [13]:
# dot product
a = np.array([1, 2])
b = np.array([10, 20])
np.dot(a, b)

50

In [ ]:
# initialize best average reward
best_avg_reward = -math.inf

In [22]:
import numpy as np
nA = 3
print(np.arange(nA))
prob = np.ones(nA) / nA
np.random.choice(np.arange(nA), p=prob)

[0 1 2]


2

In [25]:
nA = 5
np.random.choice(np.arange(nA))

4

In [2]:
# https://gym.openai.com/docs/#spaces
import gym
import gym.spaces
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)
#> Box(4,)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Discrete(2)
Box(4,)


c:\users\simon.chauvin\documents\private github\gym\gym\__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')


In [ ]:
# np.digitize
# Return the indices of the bins to which each value in input array belongs.
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
inds

In [8]:
# print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)
a = 5
print("a =", a, a, sep='00000', end='\n\n\n')

a =000005000005




In [6]:
# repr - to print a list
samples = np.array([[-1.0 , -5.0], [-0.81, -4.1], [-0.8 , -4.0],])
print(samples)
print("\nSamples:", repr(samples), sep="\n")

[[-1.   -5.  ]
 [-0.81 -4.1 ]
 [-0.8  -4.  ]]

Samples:
array([[-1.  , -5.  ],
       [-0.81, -4.1 ],
       [-0.8 , -4.  ]])


In [12]:
# transpose, honrizontal stack and [:, 1:]
low = [-1.0, -5.0]
high = [1.0, 5.0]
grid = [np.array([1, 2, 3, 4]), np.array([11, 12, 13, 14])]
res = np.hstack((np.array([low]).T, grid, np.array([high]).T))
print(res)
res[:, 1:] * 2

[[-1.  1.  2.  3.  4.  1.]
 [-5. 11. 12. 13. 14.  5.]]


array([[ 2.,  4.,  6.,  8.,  2.],
       [22., 24., 26., 28., 10.]])

In [28]:
# 3 actions and 4*4 state space
state_grid = [
    np.array([-1.02, -0.84, -0.66, -0.48]),
    np.array([-5.600e-02, -4.200e-02, -2.800e-02, -1.400e-02])
]
action_size = 3
state_size = tuple(len(splits) + 1 for splits in state_grid)  # (4+1, 4+1)
print("state_size = {}".format(state_size))

state_size = (5, 5)


In [56]:
# add tuples - with "," to specify that it is a tuple
# res[block=y][row=x][column=action] - imagine it in 3d - pack them + apply rotation
shape = (5, 5) + (3,)  # (5, 5, 3)
res = np.zeros(shape=(shape))
# print(np.zeros(shape=(2,3,4)))
res[4][3][0] = 1  # target a specific point
state = (2, 2)  # access with a tuple (apply to all actions) - not a list
res[state] = 2
state = [0, 1]  # access with a list is different does not work (it only considers the first element)
res[state] = 4
print(res)

[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [2. 2. 2.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]]]


In [55]:
max_avg_score = -np.inf

1

In [2]:
# pandas rolling window
import pandas as pd
import numpy as np
scores = [1, 2, 2, 3, 3, 2, 4, 5, 5, 8, 6, 10]
avg_score = np.mean(scores[-3:]) # average on the last 3 scores
print(avg_score)
rolling_window = 2
rolling_mean = pd.Series(scores).rolling(rolling_window).mean()
print(rolling_mean)

8.0
0     NaN
1     1.5
2     2.0
3     2.5
4     3.0
5     2.5
6     3.0
7     4.5
8     5.0
9     6.5
10    7.0
11    8.0
dtype: float64


In [3]:
import numpy as np
import matplotlib.pyplot as plt

# Set plotting options
%matplotlib inline
plt.style.use('ggplot')
np.set_printoptions(precision=3, linewidth=120)

In [13]:
# 
elements = [1, 2, 3, 4]
key = 'a'
res0 = map(lambda e: (e, key), elements)

# or zip list with a single element
import itertools
res1 = zip(elements, itertools.repeat(key))
print(set(res0))
print(list(res1))

{(4, 'a'), (1, 'a'), (2, 'a'), (3, 'a')}
[(1, 'a'), (2, 'a'), (3, 'a'), (4, 'a')]


In [16]:
# list comprehention with several objects
tiling_specs = [((10, 10), (-0.066, -0.33)),  # with tuple
                [(10, 10), (0.0, 0.0)]]  # with list
for bins, offsets in tiling_specs:
    print("bins={}, offsets={}".format(bins, offsets))

bins=(10, 10), offsets=(-0.066, -0.33)
bins=(10, 10), offsets=(0.0, 0.0)


In [18]:
# make a unzip for list comprehension
bins=(10, 10)
offsets=(5.0, 2.0)
low = (-1, 1)
high = (0, 2)
res = list(zip(*[low, high, bins, offsets]))
print(res)
# list comprehension
[(low + high, offset + binn) for low, high, binn, offset in res]

[(-1, 0, 10, 5.0), (1, 2, 10, 2.0)]


[(-1, 15.0), (3, 12.0)]

In [22]:
sample = (-1.2, -5.1)
grid = [
    np.array([-0.866, -0.666, -0.466, -0.266, -0.066,  0.134,  0.334,  0.534,  0.734]),
    np.array([-4.33, -3.33, -2.33, -1.33, -0.33,  0.67,  1.67,  2.67,  3.67])
]
list(zip(sample, grid))

In [28]:
# flatten tuple
my_list = [(1, 0), (2, 0), (3, 4)]
res0 = list((np.array(my_list)).flatten())  # numpy flatten
print(res0)
res1 = np.concatenate(my_list)  # numpy concatenate
print(res1)

[1, 0, 2, 0, 3, 4]
[1 0 2 0 3 4]
